-- Table: analysis.nces_optring

-- DROP TABLE analysis.nces_optring;

CREATE TABLE analysis.nces_optring
(
  gid integer NOT NULL,
  survyear numeric,
  ncessch character varying(31),
  fipst numeric,
  leaid numeric,
  schno numeric,
  stid character varying(15),
  seasch character varying(16),
  latcod numeric,
  loncod numeric,
  leanm character varying(61),
  schnam character varying(51),
  phone character varying(11),
  mstree character varying(31),
  mcity character varying(26),
  mstate character varying(3),
  mzip character varying(6),
  mzip4 character varying(5),
  lstree character varying(31),
  lcity character varying(26),
  lstate character varying(3),
  lzip character varying(6),
  lzip4 character varying(5),
  type numeric,
  status numeric,
  ulocal character varying(3),
  conum character varying(6),
  coname character varying(34),
  cdcode character varying(5),
  level character varying(2),
  titleistat character varying(2),
  titlei character varying(2),
  stitli character varying(2),
  magnet character varying(2),
  chartr character varying(2),
  shared character varying(2),
  frelch numeric,
  redlch numeric,
  totfrl numeric,
  racecat numeric,
  pk numeric,
  kg numeric,
  g01 numeric,
  g02 numeric,
  g03 numeric,
  g04 numeric,
  g05 numeric,
  g06 numeric,
  g07 numeric,
  g08 numeric,
  g09 numeric,
  g10 numeric,
  g11 numeric,
  g12 numeric,
  ug numeric,
  member numeric,
  am numeric,
  amalm numeric,
  amalf numeric,
  asian numeric,
  asalm numeric,
  asalf numeric,
  hisp numeric,
  hialm numeric,
  hialf numeric,
  black numeric,
  blalm numeric,
  blalf numeric,
  white numeric,
  whalm numeric,
  whalf numeric,
  pacific numeric,
  hpalm numeric,
  hpalf numeric,
  tr numeric,
  tralm numeric,
  tralf numeric,
  toteth numeric,
  id double precision,
  geom geometry,
  gid_closest numeric,
  address numeric,
  block numeric,
  cai numeric,
  middlemile numeric,
  road numeric,
  optgid numeric,
  optdist numeric,
  optring integer,
  mandist numeric,
  CONSTRAINT analysis_nces_optring_pkey PRIMARY KEY (gid ),
  CONSTRAINT enforce_dims_geom CHECK (st_ndims(geom) = 2),
  CONSTRAINT enforce_geotype_geom CHECK (geometrytype(geom) = 'POINT'::text OR geom IS NULL),
  CONSTRAINT enforce_srid_geom CHECK (st_srid(geom) = 4326)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE analysis.nces_optring
  OWNER TO postgres;

copy analysis.nces_optring
	from '/Users/FCC/Dropbox/Datasets/nces_optring.csv'
	csv header delimiter '|';
