drop table if exists analysis.imls_lib_stats;
CREATE TABLE analysis.imls_lib_stats
(
	stabr character varying(2),
	fscskey character varying(6),
	libid character varying(20),
	libname character varying(100),
	address character varying(100),
	city character varying(50),
	zip character varying(5),
	zip4 character varying(4),
	address_m character varying(50),
	city_m character varying(50),
	zip_m character varying(5),
	zip4_m character varying(4),
	cnty character varying(50),
	phone character varying(10),
	c_relatn character varying(3),
	c_legbas character varying(2),
	c_admin character varying(2),
	c_fscs character varying(1),
	geocode character varying(3),
	lsabound character varying(1),
	startdat character varying(10), 
	f_stdat character varying(4),
	enddate character varying(10),
	f_enddat character varying(4),
	popu_lsa int,
	f_poplsa character varying(4),
	popu_und int,
	f_popund character varying(4),
	centlib int,
	f_cenlib character varying(4),
	branlib int,
	f_brlib character varying(4),
	bkmob int,
	f_bkmob character varying(4),
	master float,
	f_master character varying(4),
	libraria float,
	f_librar character varying(4),
	othpaid float,
	f_othstf character varying(4),
	totstaff float,
	f_totstf character varying(4),
	locgvt int,
	f_locgvt character varying(4),
	stgvt int,
	f_stgvt character varying(4),
	fedgvt int,
	f_fedgvt character varying(4),
	othinc int,
	f_othinc character varying(4),
	totincm int,
	f_totinc character varying(4),
	salaries int,
	f_salx character varying(4),
	benefit int,
	f_benx character varying(4),
	staffexp int,
	f_tostfx character varying(4),
	prmatexp int,
	f_prmatx character varying(4),
	elmatexp int,
	f_elmatx character varying(4),
	othmatex int,
	f_otmatx character varying(4),
	totexpco int,
	f_tocolx character varying(4),
	othopexp int,
	f_othopx character varying(4),
	totopexp int,
	f_totopx character varying(4),
	lcap_rev int,
	f_lcaprv character varying(4),
	scap_rev int,
	f_scaprv character varying(4),
	fcap_rev int,
	f_fcaprv character varying(4),
	ocap_rev int,
	f_ocaprv character varying(4),
	cap_rev int,
	f_tcaprv character varying(4),
	capital int,
	f_tcapx character varying(4),
	bkvol int,
	f_bkvol character varying(4),
	ebook int,
	f_ebook character varying(4),
	audio_ph int,
	f_aud_ph character varying(4),
	audio_dl int,
	f_aud_dl character varying(4),
	video_ph int,
	f_vid_ph character varying(4),
	video_dl int,
	f_vid_dl character varying(4),
	db_lo_ot int,
	f_db_l_o character varying(4),
	db_st int,
	f_db_st character varying(4),
	database int,
	f_dbase character varying(4),
	subscrip int,
	f_prsub character varying(4),
	hrs_open int,
	f_hrs_op character varying(4),
	visits int,
	f_visits character varying(4),
	referenc int,
	f_refer character varying(4),
	regbor int,
	f_regbor character varying(4),
	totcir int,
	f_totcir character varying(4),
	kidcircl int,
	f_kidcircl character varying(4),
	loanto int,
	f_loanto character varying(4),
	loanfm int,
	f_loanfm character varying(4),
	totpro int,
	f_totpro character varying(4),
	kidpro int,
	f_kidpro character varying(4),
	yapro int,
	f_yapro character varying(4),
	totatten int,
	f_totatt character varying(4),
	kidatten int,
	f_kidatt character varying(4),
	yaatten int,
	f_yaatt  character varying(4),
	gpterms int,
	f_gpterm character varying(4),
	pitusr int,
	f_pitusr character varying(4),
	yr_sub int,
	obereg int,
	rstatus int, 
	statstru int,
	statname int,
	stataddr int,
	longitud double precision,
	latitude double precision,
	fipsst character varying(2),
	fipsco character varying(3),
	fipslac character varying(5),
	cntypop int,
	locale int,
	centract character varying(10),
	cenblock character varying(4),
	cdcode character varying(5),
	cbsa character varying(5),
	microf character varying(2),
	gal character varying(20),
	galms character varying(3),
	postms character varying(3)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE analysis.imls_lib_stats
  OWNER TO postgres;

set client_encoding to 'latin1';
copy analysis.imls_lib_stats
	from '/Users/FCC/Documents/allison/E-rate analysis/Data/PLS 2012/pupld12a_csv/Pupld12a.csv'
	csv header delimiter ',';
