--CREATE TABLE
DROP TABLE IF EXISTS analysis.nces_public_2011;
CREATE TABLE analysis.nces_public_2011
(
	SURVYEAR character varying(4),
	NCESSCH	character varying(12) PRIMARY KEY,
	FIPST character varying(2),
	LEAID character varying(7),
	SCHNO character varying(5),
	STID character varying(15),
	SEASCH character varying(20),
	LEANM character varying(150),
	SCHNAM character varying(150),
	PHONE character varying(10),
	MSTREE character varying(200),
	MCITY character varying(50),
	MSTATE character varying(2),	
	MZIP character varying(5),
	MZIP4 character varying(4),
	LSTREE character varying(200),
	LCITY character varying(50),
	LSTATE character varying(2),	
	LZIP character varying(5),
	LZIP4 character varying(4),
	TYPE character varying(2),	
	STATUS character varying(2),
	UNION_ID character varying(10),	
	ULOCAL character varying(2),	
	LATCOD double precision,
	LONCOD	double precision,
	CONUM character varying(5),	
	CONAME character varying(100),
	CDCODE character varying(6),
	CDCODE_112 character varying(6),	
	BIES character varying(2),	
	RECONSTY character varying(4),	
	RECONSTF character varying(2),
	SMEMPUP character varying(2),
	ISMEMPUP character varying(2),
	SFTEPUP	character varying(2),
	ISFTEPUP character varying(2),
	SFLE character varying(2),
	ISFLE character varying(2),
	SPFEMALE character varying(2),
	ISPFEMALE character varying(2),
	SPWHITE	character varying(2),
	ISPWHITE character varying(2),
	SPELM character varying(2),
	ISPELM character varying(2),
	FTE float,
	GSLO character varying(2),
	GSHI character varying(2),
	PKOFFRD	character varying(2),
	KGOFFRD	character varying(2),
	G01OFFRD character varying(2),
	G02OFFRD character varying(2),
	G03OFFRD character varying(2),
	G04OFFRD character varying(2),
	G05OFFRD character varying(2),
	G06OFFRD character varying(2),
	G07OFFRD character varying(2),
	G08OFFRD character varying(2),
	G09OFFRD character varying(2),
	G10OFFRD character varying(2),
	G11OFFRD character varying(2),
	G12OFFRD character varying(2),
	UGOFFRD	character varying(2),
	LEVEL character varying(2),
	TITLEISTAT character varying(2),
	TITLEI character varying(2),
	STITLI character varying(2),
	MAGNET character varying(2),
	CHARTR	character varying(2),
	SHARED	character varying(2),
	FRELCH	integer,
	REDLCH	integer,
	TOTFRL	integer,
	RACECAT	character varying(2),
	PK integer,
	AMPKM integer,
	AMPKF integer,
	ASPKM integer,
	ASPKF integer,
	HIPKM integer,
	HIPKF integer,
	BLPKM integer,
	BLPKF integer,
	WHPKM integer,
	WHPKF integer,
	HPPKM integer,
	HPPKF integer,
	TRPKM integer,
	TRPKF integer,
	KG integer,
	AMKGM integer,
	AMKGF integer,
	ASKGM integer,
	ASKGF integer,
	HIKGM integer,
	HIKGF integer,
	BLKGM integer,
	BLKGF integer,
	WHKGM integer,
	WHKGF integer,
	HPKGM integer,
	HPKGF integer,
	TRKGM integer,
	TRKGF integer,
	G01 integer,
	AM01M integer,
	AM01F integer,
	AS01M integer,
	AS01F integer,
	HI01M integer,
	HI01F integer,
	BL01M integer,
	BL01F integer,
	WH01M integer,
	WH01F integer,
	HP01M integer,
	HP01F integer,
	TR01M integer,
	TR01F integer,
	G02 integer,
	AM02M integer,
	AM02F integer,
	AS02M integer,
	AS02F integer,
	HI02M integer,
	HI02F integer,
	BL02M integer,
	BL02F integer,
	WH02M integer,
	WH02F integer,
	HP02M integer,
	HP02F integer,
	TR02M integer,
	TR02F integer,
	G03 integer,
	AM03M integer,
	AM03F integer,
	AS03M integer,
	AS03F integer,
	HI03M integer,
	HI03F integer,
	BL03M integer,
	BL03F integer,
	WH03M integer,
	WH03F integer,
	HP03M integer,
	HP03F integer,
	TR03M integer,
	TR03F integer,
	G04 integer,
	AM04M integer,
	AM04F integer,
	AS04M integer,
	AS04F integer,
	HI04M integer,
	HI04F integer,
	BL04M integer,
	BL04F integer,
	WH04M integer,
	WH04F integer,
	HP04M integer,
	HP04F integer,
	TR04M integer,
	TR04F integer,
	G05 integer,
	AM05M integer,
	AM05F integer,
	AS05M integer,
	AS05F integer,
	HI05M integer,
	HI05F integer,
	BL05M integer,
	BL05F integer,
	WH05M integer,
	WH05F integer,
	HP05M integer,
	HP05F integer,
	TR05M integer,
	TR05F integer,
	G06 integer,
	AM06M  integer,	
	AM06F integer,	
	AS06M integer,
	AS06F integer,
	HI06M integer,
	HI06F integer,
	BL06M integer,
	BL06F integer,
	WH06M integer,
	WH06F integer,
	HP06M integer,
	HP06F integer,
	TR06M integer,
	TR06F integer,
	G07 integer,
	AM07M integer,
	AM07F integer,
	AS07M integer,
	AS07F integer,
	HI07M integer,
	HI07F integer,
	BL07M integer,
	BL07F integer,
	WH07M integer,
	WH07F integer,
	HP07M integer,
	HP07F integer,
	TR07M integer,
	TR07F integer,
	G08 integer,
	AM08M integer,
	AM08F integer,
	AS08M integer,
	AS08F integer,
	HI08M integer,
	HI08F integer,
	BL08M integer,
	BL08F integer,
	WH08M integer,
	WH08F integer,
	HP08M integer,
	HP08F integer,
	TR08M integer,
	TR08F integer,
	G09 integer,
	AM09M integer,
	AM09F integer,
	AS09M integer,	
	AS09F integer,
	HI09M integer,
	HI09F integer,	
	BL09M integer,	
	BL09F integer,	
	WH09M integer,
	WH09F integer,	
	HP09M integer,	
	HP09F integer,	
	TR09M integer,
	TR09F integer,
	G10 integer,	
	AM10M integer,
	AM10F integer,	
	AS10M integer,
	AS10F integer,
	HI10M integer,	
	HI10F integer,
	BL10M integer,
	BL10F integer,
	WH10M integer,	
	WH10F integer,	
	HP10M integer,
	HP10F integer,
	TR10M integer,
	TR10F integer,
	G11 integer,
	AM11M integer,
	AM11F integer,
	AS11M integer,
	AS11F integer,
	HI11M integer,	
	HI11F integer,
	BL11M integer,	
	BL11F integer,	
	WH11M integer,	
	WH11F integer,	
	HP11M integer,	
	HP11F integer,
	TR11M integer,	
	TR11F integer,	
	G12 integer,
	AM12M integer,
	AM12F integer,	
	AS12M integer,	
	AS12F integer,
	HI12M integer,
	HI12F integer,	
	BL12M integer,
	BL12F integer,
	WH12M integer,
	WH12F integer,
	HP12M integer,
	HP12F integer,	
	TR12M integer,
	TR12F integer,
	UG integer,
	AMUGM integer,
	AMUGF integer,
	ASUGM integer,
	ASUGF integer,
	HIUGM integer,
	HIUGF integer,	
	BLUGM integer,
	BLUGF integer,
	WHUGM integer,
	WHUGF integer,
	HPUGM integer,	
	HPUGF integer,	
	TRUGM integer,	
	TRUGF integer,	
	MEMBER integer,	
	AM integer,
	AMALM integer,
	AMALF integer,
	ASIAN integer,	
	ASALM integer,
	ASALF integer,
	HISP integer,
	HIALM integer,
	HIALF integer,	
	BLACK integer,
	BLALM integer,
	BLALF integer,
	WHITE integer,	
	WHALM integer,
	WHALF integer,
	PACIFIC integer,
	HPALM integer,	
	HPALF integer,	
	TR integer,	
	TRALM integer,	
	TRALF integer,	
	TOTETH integer	
)	
WITH (
  OIDS=FALSE
);
ALTER TABLE analysis.nces_public_2011
  OWNER TO postgres;

SET client_encoding to 'latin1';
COPY analysis.nces_public_2011
	FROM '/Users/FCC/Documents/allison/data/public_school/sc111a_supp_apr21.txt';

--ADD GEOMETRY
ALTER table analysis.nces_public_2011 ADD COLUMN geom geometry(POINT,4326);
UPDATE analysis.nces_public_2011 SET geom = ST_SetSRID(ST_MakePoint(loncod,latcod),4326);
CREATE INDEX nces_public_2011_geom_gist ON analysis.nces_public_2011 USING GIST(geom);

--DROP FOREIGN DOD SCHOOLS
DELETE FROM analysis.nces_public_2011
WHERE FIPST = '63' AND latcod = 0 AND loncod = 0;